### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by 472405746** [Lagrang/CuratorNet#1]
hi ,way when  my project build  output some of errors? 
thanks #

**Comment by Lagrang** [comment]
Hello!
Project still in progress and unfortunately doesn't finished yet.

**Comment by 472405746** [comment]
hi, When will it end?

**Comment by Lagrang** [comment]
This is my "home" project, I spent my free time to it. No roadmap for it, sorry
This is "line-by-line" port of Curator and it requires a long time to finish it
